### ISSUE TITLE
input issue on cemu 1.12.2d

### ISSUE THREAD

**Issue by jdsmith2816** [SteveLeafo/Budford#20]
Using an xbox one controller with Budford and Cemu 1.12.2d I can configure input as expected using the input dialog but the game itself actually ignores the controller.

I deleted the Budford cemu_1.12.2 to manually install a fresh cemu 1.12.2d + latest cemuhook.  Upon booting it up, configuring input exactly the same way, and loading the same game... everything worked as expected.

I next tried launching the now confirmed working cemu installation via budford and the problem came back...  The problem now persists for this installation whether or not cemu is launched via budford or manually.

This problem does not exist for the cemu installed via the "Download Old Releases -> 1.8.2" so maybe it's related to the most recent 1.12.2d which came out shortly after your last update?

Do you have any idea what might be happening?

**Comment by SteveLeafo** [comment]
I think in might be the Cemu Hook option "Motion Source is Button Source".

Budford sets this to be enabled by default. When you launch a game via Budford it will update the Cemuhook.ini file which is why it persists even when you don't use Budford.

You can disable it in Budford then launch a game or edit / delete the Cemuhook.ini file.

**Comment by jdsmith2816** [comment]
That was it.  Thanks!
