### ISSUE TITLE
Could not find game with id - shader cache import

### ISSUE THREAD

**Issue by IceLancerSR** [SteveLeafo/Budford#3]
https://i.imgur.com/h12Gfd0l.jpg
Game is right there, it doesnt wish to import any cache except for zelda.Keep saying game doesnt exist

And please make that portable as well, dont copy shaders to my documents..

**Comment by SteveLeafo** [comment]
Hi, thanks for raising this issue.

The problem was that Budford was unable to match the SaveDir from the shader cache file name with any of the games it found.  As of V1.0.52, when this occurs in future, Budford will now prompt you to select the correct game from the list.

As of V1.0.51 the Install folder will now contains a zip file that you can extract and run. Also, it is now possible to configure the Download and Save folders.

I hope this helps you to get Budford up and running.

Regards,
Leafo
